<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Str;

class ProductoClaseSubclaseSeeder extends Seeder
{
    public function run(): void
    {
        Schema::disableForeignKeyConstraints();
        DB::table('products_subclases')->truncate();
        DB::table('products_clases')->truncate();
        Schema::enableForeignKeyConstraints();

        $now = now();
        $clases = $this->clasesData();
        $claseUlids = [];
        $usedClaseSlugs = [];

        foreach ($clases as $c) {
            $ulid = (string) Str::ulid();
            $codigo = 'CLS-'.str_pad((string) $c['orden'], 5, '0', STR_PAD_LEFT);
            $slug = $this->uniqueSlug($c['nombre'], $usedClaseSlugs);
            $claseUlids[$c['nombre']] = $ulid;

            DB::table('products_clases')->insert([
                'id' => $ulid,
                'codigo' => $codigo,
                'nombre' => $c['nombre'],
                'slug' => $slug,
                'licor' => $c['licor'],
                'orden' => $c['orden'],
                'activo' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ]);
        }

        $subclases = $this->subclasesData();
        $usedSubclaseSlugs = [];
        $codigoIdx = 0;

        foreach ($subclases as $s) {
            $codigoIdx++;
            $ulid = (string) Str::ulid();
            $codigo = 'SCL-'.str_pad((string) $codigoIdx, 5, '0', STR_PAD_LEFT);
            $slug = $this->uniqueSlug($s['nombre'], $usedSubclaseSlugs);

            DB::table('products_subclases')->insert([
                'id' => $ulid,
                'clase_id' => $claseUlids[$s['clase_nombre']],
                'codigo' => $codigo,
                'nombre' => $s['nombre'],
                'slug' => $slug,
                'orden' => $s['orden'],
                'activo' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ]);
        }
    }

    private function uniqueSlug(string $name, array &$used): string
    {
        $base = Str::slug($name);
        $slug = $base;
        $counter = 1;
        while (in_array($slug, $used, true)) {
            $slug = $base.'-'.$counter;
            $counter++;
        }
        $used[] = $slug;

        return $slug;
    }

    private function clasesData(): array
    {
        return [
            ['orden' => 1, 'nombre' => 'PANASONIC', 'licor' => false],
            ['orden' => 2, 'nombre' => 'GRUPO BIMBO', 'licor' => false],
            ['orden' => 3, 'nombre' => 'MI FARMA', 'licor' => false],
            ['orden' => 4, 'nombre' => 'RADIANTE', 'licor' => false],
            ['orden' => 5, 'nombre' => 'COCK BRAND', 'licor' => false],
            ['orden' => 6, 'nombre' => 'LABOCER', 'licor' => false],
            ['orden' => 7, 'nombre' => 'FOPESA', 'licor' => false],
            ['orden' => 8, 'nombre' => 'INKACROPS', 'licor' => false],
            ['orden' => 9, 'nombre' => 'QUALA', 'licor' => false],
            ['orden' => 10, 'nombre' => 'GRUPO HUANCARUNA', 'licor' => false],
            ['orden' => 11, 'nombre' => 'SAN JORGE', 'licor' => false],
            ['orden' => 12, 'nombre' => 'INDUPSA', 'licor' => false],
            ['orden' => 13, 'nombre' => 'SIBARITA', 'licor' => false],
            ['orden' => 14, 'nombre' => 'EDGEWELL PERSONAL CARE', 'licor' => false],
            ['orden' => 15, 'nombre' => 'ENVASADORA MAJES', 'licor' => false],
            ['orden' => 16, 'nombre' => 'SUPERALIMENTOS', 'licor' => false],
            ['orden' => 17, 'nombre' => 'DELYCORP', 'licor' => false],
            ['orden' => 18, 'nombre' => 'ALICORP', 'licor' => false],
            ['orden' => 19, 'nombre' => 'ISM', 'licor' => false],
            ['orden' => 20, 'nombre' => 'VALLE ICA', 'licor' => false],
            ['orden' => 21, 'nombre' => 'COLGATE', 'licor' => false],
            ['orden' => 22, 'nombre' => 'CONFITECA', 'licor' => false],
            ['orden' => 23, 'nombre' => 'ACONCAGUA', 'licor' => false],
            ['orden' => 24, 'nombre' => 'COCA-COLA', 'licor' => false],
            ['orden' => 25, 'nombre' => 'JOHNSON & JOHNSON', 'licor' => false],
            ['orden' => 26, 'nombre' => 'SUPER GLUE', 'licor' => false],
            ['orden' => 27, 'nombre' => 'ARCOR', 'licor' => false],
            ['orden' => 28, 'nombre' => 'PEPSICO', 'licor' => false],
            ['orden' => 29, 'nombre' => 'PROCTER & GAMBLE (P&G)', 'licor' => false],
            ['orden' => 30, 'nombre' => 'QUIMPAC', 'licor' => false],
            ['orden' => 31, 'nombre' => 'IMPERIAL BRANDS', 'licor' => false],
            ['orden' => 32, 'nombre' => 'PROTISA', 'licor' => false],
            ['orden' => 33, 'nombre' => 'MONDELEZ', 'licor' => false],
            ['orden' => 34, 'nombre' => 'UNILEVER', 'licor' => false],
            ['orden' => 35, 'nombre' => 'LIVINI', 'licor' => false],
            ['orden' => 36, 'nombre' => 'ALSOL', 'licor' => false],
            ['orden' => 37, 'nombre' => 'GOLOPERU', 'licor' => false],
            ['orden' => 38, 'nombre' => 'ALIMENTOS CIELO S.A.C.', 'licor' => false],
            ['orden' => 39, 'nombre' => 'ANDINA ALIMENTOS', 'licor' => false],
            ['orden' => 40, 'nombre' => 'DISTRIBUIDORA JANDY', 'licor' => false],
            ['orden' => 41, 'nombre' => 'PAPELERA REYES', 'licor' => false],
            ['orden' => 42, 'nombre' => 'INCASUR', 'licor' => false],
            ['orden' => 44, 'nombre' => 'SODA LIMON', 'licor' => false],
            ['orden' => 46, 'nombre' => 'LUCKY STRIKE', 'licor' => false],
            ['orden' => 47, 'nombre' => 'MOLINOS RIO DE LA PLATA S.A.', 'licor' => false],
            ['orden' => 48, 'nombre' => 'HONG HUA', 'licor' => false],
            ['orden' => 49, 'nombre' => '2 CERRITOS', 'licor' => false],
            ['orden' => 51, 'nombre' => 'NESTLE', 'licor' => false],
            ['orden' => 52, 'nombre' => 'AJE', 'licor' => false],
            ['orden' => 53, 'nombre' => 'HENKEL', 'licor' => false],
            ['orden' => 54, 'nombre' => 'WINTER\'S', 'licor' => false],
            ['orden' => 58, 'nombre' => 'ZUKO', 'licor' => false],
            ['orden' => 59, 'nombre' => 'MOLITALIA', 'licor' => false],
            ['orden' => 60, 'nombre' => 'BUCKY', 'licor' => false],
            ['orden' => 61, 'nombre' => 'NOSOTRAS', 'licor' => false],
            ['orden' => 62, 'nombre' => 'AJI-NO-MOTO', 'licor' => false],
            ['orden' => 63, 'nombre' => 'GLORIA', 'licor' => false],
            ['orden' => 66, 'nombre' => 'HERBI', 'licor' => false],
            ['orden' => 68, 'nombre' => 'KIKKO', 'licor' => false],
            ['orden' => 69, 'nombre' => 'AREQUEPAY', 'licor' => false],
            ['orden' => 70, 'nombre' => 'COLOMBINA', 'licor' => false],
            ['orden' => 71, 'nombre' => 'FAGY PERU', 'licor' => false],
            ['orden' => 72, 'nombre' => 'MEDIFARMA', 'licor' => false],
            ['orden' => 73, 'nombre' => 'BAHIA', 'licor' => false],
            ['orden' => 74, 'nombre' => 'CLASICO', 'licor' => false],
            ['orden' => 75, 'nombre' => 'P.A.N.', 'licor' => false],
            ['orden' => 76, 'nombre' => 'IQUEÑITA', 'licor' => false],
            ['orden' => 77, 'nombre' => 'YICHANG & CIA', 'licor' => false],
            ['orden' => 78, 'nombre' => 'SOFTYS', 'licor' => false],
            ['orden' => 79, 'nombre' => 'KIMBERLY-CLARK', 'licor' => false],
            ['orden' => 80, 'nombre' => 'DON MAXIMO', 'licor' => false],
            ['orden' => 81, 'nombre' => 'EL ROJITO', 'licor' => false],
            ['orden' => 82, 'nombre' => 'GRUPO FALABELA', 'licor' => false],
            ['orden' => 83, 'nombre' => 'MEGAPLAST', 'licor' => false],
            ['orden' => 84, 'nombre' => 'BACKUS', 'licor' => true],
            ['orden' => 85, 'nombre' => 'SOMELE', 'licor' => false],
            ['orden' => 86, 'nombre' => 'POMALCA', 'licor' => false],
            ['orden' => 87, 'nombre' => 'BORANI', 'licor' => false],
        ];
    }

    private function subclasesData(): array
    {
        return [
            ['orden' => 1, 'clase_nombre' => 'SIBARITA', 'nombre' => 'POLVOS SIBARITA'],
            ['orden' => 2, 'clase_nombre' => 'MONDELEZ', 'nombre' => 'CHICLE TRIDENT'],
            ['orden' => 3, 'clase_nombre' => 'SIBARITA', 'nombre' => 'PASTAS SIBARITA'],
            ['orden' => 4, 'clase_nombre' => 'SIBARITA', 'nombre' => 'PASTAS MERI'],
            ['orden' => 5, 'clase_nombre' => 'AJE', 'nombre' => 'AJE PULP'],
            ['orden' => 6, 'clase_nombre' => 'SIBARITA', 'nombre' => 'POLVOS MERI'],
            ['orden' => 7, 'clase_nombre' => 'SIBARITA', 'nombre' => 'VINAGRE SIBARITA'],
            ['orden' => 8, 'clase_nombre' => 'ACONCAGUA', 'nombre' => 'CONSERVAS ACONCAGUA'],
            ['orden' => 9, 'clase_nombre' => 'SAN JORGE', 'nombre' => 'WAFER SAN JORGE'],
            ['orden' => 10, 'clase_nombre' => 'SAN JORGE', 'nombre' => 'GALLETAS SAN JORGE'],
            ['orden' => 11, 'clase_nombre' => 'ALICORP', 'nombre' => 'DETERGENTE OPAL'],
            ['orden' => 12, 'clase_nombre' => 'MONDELEZ', 'nombre' => 'HALLS MONDELEZ'],
            ['orden' => 13, 'clase_nombre' => 'MOLITALIA', 'nombre' => 'CHICLETS AMBROSOLI'],
            ['orden' => 14, 'clase_nombre' => 'MOLITALIA', 'nombre' => 'GOMITAS AMBROSOLI'],
            ['orden' => 15, 'clase_nombre' => 'PROTISA', 'nombre' => 'PH ELITE'],
            ['orden' => 16, 'clase_nombre' => 'MOLITALIA', 'nombre' => 'CHUPETIN AMBROSOLI'],
            ['orden' => 17, 'clase_nombre' => 'MOLITALIA', 'nombre' => 'MASTICABLES AMBROSOLI'],
            ['orden' => 18, 'clase_nombre' => 'PANASONIC', 'nombre' => 'BATERIAS/PILAS PANASONIC'],
            ['orden' => 22, 'clase_nombre' => 'COCK BRAND', 'nombre' => 'INCECTICIDA ESPIRAL'],
            ['orden' => 23, 'clase_nombre' => 'INDUPSA', 'nombre' => 'AVENA SANTA CATALINA'],
            ['orden' => 24, 'clase_nombre' => 'MONDELEZ', 'nombre' => 'GALLETAS FIELD'],
            ['orden' => 25, 'clase_nombre' => 'MONDELEZ', 'nombre' => 'CHICLE BUBBALOO'],
            ['orden' => 26, 'clase_nombre' => 'COCK BRAND', 'nombre' => 'INSECTITICIDA SPRAY'],
            ['orden' => 27, 'clase_nombre' => 'PEPSICO', 'nombre' => 'SNAKS LAYS'],
            ['orden' => 28, 'clase_nombre' => 'ANDINA ALIMENTOS', 'nombre' => 'PANETON RICCO\'S'],
            ['orden' => 29, 'clase_nombre' => 'FOPESA', 'nombre' => 'FOSFORO INTI'],
            ['orden' => 30, 'clase_nombre' => 'GRUPO HUANCARUNA', 'nombre' => 'CAFE ALTOMAYO'],
            ['orden' => 31, 'clase_nombre' => 'ISM', 'nombre' => 'ENERGIZANTE 360'],
            ['orden' => 32, 'clase_nombre' => 'WINTER\'S', 'nombre' => 'COCOA WINTER\'S'],
            ['orden' => 33, 'clase_nombre' => 'AJI-NO-MOTO', 'nombre' => 'DOÑA GUSTA'],
            ['orden' => 34, 'clase_nombre' => 'AJI-NO-MOTO', 'nombre' => 'AJINOMOTO'],
            ['orden' => 35, 'clase_nombre' => 'QUALA', 'nombre' => 'TRATAMIENTO CAPILLAR'],
            ['orden' => 36, 'clase_nombre' => 'ALICORP', 'nombre' => 'DETERGENTE MARSELLA'],
            ['orden' => 37, 'clase_nombre' => 'RADIANTE', 'nombre' => 'VELA RADIANTE'],
            ['orden' => 38, 'clase_nombre' => 'MONDELEZ', 'nombre' => 'GALLETAS OREO'],
            ['orden' => 39, 'clase_nombre' => 'PEPSICO', 'nombre' => 'SNACKS CHIZITOS'],
            ['orden' => 40, 'clase_nombre' => 'PEPSICO', 'nombre' => 'SNACKS CHEETOS'],
            ['orden' => 41, 'clase_nombre' => 'PEPSICO', 'nombre' => 'SNACKS CHEESE TRIS'],
            ['orden' => 42, 'clase_nombre' => 'MONDELEZ', 'nombre' => 'CHICLETS CLORETS'],
            ['orden' => 43, 'clase_nombre' => 'PEPSICO', 'nombre' => 'SNACKS CUATES'],
            ['orden' => 44, 'clase_nombre' => 'KIMBERLY-CLARK', 'nombre' => 'PH SUAVE'],
            ['orden' => 45, 'clase_nombre' => 'ALICORP', 'nombre' => 'GALLETA CHOCOBUM'],
            ['orden' => 46, 'clase_nombre' => 'PEPSICO', 'nombre' => 'SNAKS DORITOS'],
            ['orden' => 47, 'clase_nombre' => 'GRUPO BIMBO', 'nombre' => 'SNAKS TAKIS'],
            ['orden' => 48, 'clase_nombre' => 'ALICORP', 'nombre' => 'DETERGENTE BOLIVAR'],
            ['orden' => 49, 'clase_nombre' => 'SAN JORGE', 'nombre' => 'PANETON SAN JORGE'],
            ['orden' => 50, 'clase_nombre' => 'ALICORP', 'nombre' => 'CEREALES ANGEL'],
            ['orden' => 51, 'clase_nombre' => 'MOLITALIA', 'nombre' => 'CEREAL BAR COSTA'],
            ['orden' => 52, 'clase_nombre' => 'MONDELEZ', 'nombre' => 'GALLETAS CHIPS AHOY'],
            ['orden' => 53, 'clase_nombre' => 'MONDELEZ', 'nombre' => 'WAFER CUA CUA'],
            ['orden' => 54, 'clase_nombre' => 'COCA-COLA', 'nombre' => 'GASEOSA FANTA'],
            ['orden' => 55, 'clase_nombre' => 'ALICORP', 'nombre' => 'SUAVIZANTE BOLIVAR'],
            ['orden' => 56, 'clase_nombre' => 'ISM', 'nombre' => 'BEBIDA KRIS'],
            ['orden' => 57, 'clase_nombre' => 'UNILEVER', 'nombre' => 'MAIZENA DURYEA'],
            ['orden' => 58, 'clase_nombre' => 'PEPSICO', 'nombre' => 'REHIDRATANTE GATORADE'],
            ['orden' => 59, 'clase_nombre' => 'LABOCER', 'nombre' => 'CHICLE BUZZY'],
            ['orden' => 60, 'clase_nombre' => 'QUALA', 'nombre' => 'SHAMPOO'],
            ['orden' => 61, 'clase_nombre' => 'KIMBERLY-CLARK', 'nombre' => 'PAÑALES HUGGIES'],
            ['orden' => 62, 'clase_nombre' => 'SIBARITA', 'nombre' => 'VINAGRE MERI'],
            ['orden' => 63, 'clase_nombre' => 'JOHNSON & JOHNSON', 'nombre' => 'JABON CORPORAL NEKO'],
            ['orden' => 64, 'clase_nombre' => 'BACKUS', 'nombre' => 'CERVEZA CRISTAL'],
            ['orden' => 65, 'clase_nombre' => 'SAN JORGE', 'nombre' => 'CONSERVA DE PESCADO'],
            ['orden' => 66, 'clase_nombre' => 'IMPERIAL BRANDS', 'nombre' => 'CIGARROS GOLDEN'],
            ['orden' => 67, 'clase_nombre' => 'ALICORP', 'nombre' => 'ACEITE MIRASOL'],
            ['orden' => 68, 'clase_nombre' => 'MONDELEZ', 'nombre' => 'GALLETAS RITZ'],
            ['orden' => 69, 'clase_nombre' => 'SUPER GLUE', 'nombre' => 'PEGAMENTO SUPER GLUE'],
            ['orden' => 70, 'clase_nombre' => 'UNILEVER', 'nombre' => 'SHAMPOO SEDAL'],
            ['orden' => 71, 'clase_nombre' => 'LIVINI', 'nombre' => 'GELATINA LIVINI'],
            ['orden' => 72, 'clase_nombre' => 'PEPSICO', 'nombre' => 'AVENA QUAKER'],
            ['orden' => 73, 'clase_nombre' => 'ALSOL', 'nombre' => 'ACEITE ALSOL'],
            ['orden' => 74, 'clase_nombre' => 'SAN JORGE', 'nombre' => 'FIDEO SAN JORGE'],
            ['orden' => 75, 'clase_nombre' => 'PEPSICO', 'nombre' => 'SNACKS CHIFLE'],
            ['orden' => 76, 'clase_nombre' => 'GOLOPERU', 'nombre' => 'CARAMELO PERUSA'],
            ['orden' => 77, 'clase_nombre' => 'ALIMENTOS CIELO S.A.C.', 'nombre' => 'ACEITE CIELO'],
            ['orden' => 78, 'clase_nombre' => 'MOLITALIA', 'nombre' => 'CHOCOLATE COSTA'],
            ['orden' => 79, 'clase_nombre' => 'MOLITALIA', 'nombre' => 'WAFER COSTA'],
            ['orden' => 80, 'clase_nombre' => 'MOLITALIA', 'nombre' => 'GALLETA COSTA'],
            ['orden' => 81, 'clase_nombre' => 'ALICORP', 'nombre' => 'GALLETAS VICTORIA'],
            ['orden' => 82, 'clase_nombre' => 'DELYCORP', 'nombre' => 'MINI GELATINA'],
            ['orden' => 83, 'clase_nombre' => 'ALICORP', 'nombre' => 'DETERGENTE PATITO'],
            ['orden' => 84, 'clase_nombre' => 'ALICORP', 'nombre' => 'DETERGENTE TROME'],
            ['orden' => 85, 'clase_nombre' => 'ZUKO', 'nombre' => 'REFRESCO ZUKO'],
            ['orden' => 86, 'clase_nombre' => 'LUCKY STRIKE', 'nombre' => 'CIGARRO LUCKY'],
            ['orden' => 87, 'clase_nombre' => 'ALICORP', 'nombre' => 'GALLETA SAYON'],
            ['orden' => 88, 'clase_nombre' => 'ALICORP', 'nombre' => 'LAVAVAJILLA SAPOLIO'],
            ['orden' => 89, 'clase_nombre' => 'MOLITALIA', 'nombre' => 'AVENA 3 OSITOS'],
            ['orden' => 90, 'clase_nombre' => 'AJE', 'nombre' => 'HIDRATANTE SPORADE'],
            ['orden' => 91, 'clase_nombre' => 'COCA-COLA', 'nombre' => 'POWER ADE'],
            ['orden' => 92, 'clase_nombre' => 'ALICORP', 'nombre' => 'SALSAS ALACENA'],
            ['orden' => 93, 'clase_nombre' => 'MOLITALIA', 'nombre' => 'SALSA MOLITALIA'],
            ['orden' => 94, 'clase_nombre' => 'NESTLE', 'nombre' => 'NESCAFE NESTLE'],
            ['orden' => 95, 'clase_nombre' => 'NESTLE', 'nombre' => 'CHOCOLATE NESTLE'],
            ['orden' => 96, 'clase_nombre' => 'ALICORP', 'nombre' => 'MANTEQUILLA SELLO DE ORO'],
            ['orden' => 97, 'clase_nombre' => 'ALICORP', 'nombre' => 'MANTEQUILLA MANTY'],
            ['orden' => 98, 'clase_nombre' => 'MOLINOS RIO DE LA PLATA S.A.', 'nombre' => 'HARINA'],
            ['orden' => 99, 'clase_nombre' => 'GLORIA', 'nombre' => 'LECHE GLORIA'],
            ['orden' => 100, 'clase_nombre' => 'NOSOTRAS', 'nombre' => 'TOALLAS HIGIENICAS'],
            ['orden' => 101, 'clase_nombre' => 'AJI-NO-MOTO', 'nombre' => 'AJINOMEN'],
            ['orden' => 102, 'clase_nombre' => 'GLORIA', 'nombre' => 'YOGURT GLORIA'],
            ['orden' => 103, 'clase_nombre' => 'MOLITALIA', 'nombre' => 'MERMELADA FANNY'],
            ['orden' => 105, 'clase_nombre' => 'COCA-COLA', 'nombre' => 'GASEOSA INCA KOLA'],
            ['orden' => 106, 'clase_nombre' => 'MOLITALIA', 'nombre' => 'BIZCOCHO COSTA'],
            ['orden' => 107, 'clase_nombre' => 'HERBI', 'nombre' => 'INFUSIONES HERBI'],
            ['orden' => 108, 'clase_nombre' => 'WINTER\'S', 'nombre' => 'CHOCOLATE CHIN CHIN'],
            ['orden' => 109, 'clase_nombre' => 'BACKUS', 'nombre' => 'CERVEZA GOLDEN'],
            ['orden' => 110, 'clase_nombre' => 'ALICORP', 'nombre' => 'LIMPIATODO SAPOLIO'],
            ['orden' => 111, 'clase_nombre' => 'KIKKO', 'nombre' => 'SILLAO KIKKO'],
            ['orden' => 112, 'clase_nombre' => 'PROCTER & GAMBLE (P&G)', 'nombre' => 'TOALLAS HIGIENICAS ALWAYS'],
            ['orden' => 113, 'clase_nombre' => 'COLOMBINA', 'nombre' => 'CHUPETIN COLOMBINA'],
            ['orden' => 114, 'clase_nombre' => 'ALICORP', 'nombre' => 'JABON DE ROPA TROME'],
            ['orden' => 115, 'clase_nombre' => 'FAGY PERU', 'nombre' => 'REPELENTE FLORESTA'],
            ['orden' => 116, 'clase_nombre' => 'MEDIFARMA', 'nombre' => 'ANTIACIDO SAL DE ANDREWS'],
            ['orden' => 117, 'clase_nombre' => 'BAHIA', 'nombre' => 'BLOQUEADOR SOLAR BAHIA'],
            ['orden' => 118, 'clase_nombre' => 'UNILEVER', 'nombre' => 'ANTITRANSPIRANTE REXONA'],
            ['orden' => 119, 'clase_nombre' => 'WINTER\'S', 'nombre' => 'GALLETAS PICARAS'],
            ['orden' => 120, 'clase_nombre' => 'IQUEÑITA', 'nombre' => 'CONSERVAS IQUEÑITA'],
            ['orden' => 121, 'clase_nombre' => 'YICHANG & CIA', 'nombre' => 'CONSERVAS FLORIDA'],
            ['orden' => 122, 'clase_nombre' => 'PROTISA', 'nombre' => 'PAÑALES BABY SEC'],
            ['orden' => 123, 'clase_nombre' => 'GRUPO FALABELA', 'nombre' => 'PANETON TOTTUS'],
            ['orden' => 124, 'clase_nombre' => 'AJE', 'nombre' => 'BEBIDA CIFRUT'],
            ['orden' => 125, 'clase_nombre' => 'DON MAXIMO', 'nombre' => 'FIDEOS DON MAXIMO'],
            ['orden' => 126, 'clase_nombre' => 'ALICORP', 'nombre' => 'ACEITE TONDERO'],
            ['orden' => 127, 'clase_nombre' => 'COCA-COLA', 'nombre' => 'COCA COLA LATA'],
            ['orden' => 128, 'clase_nombre' => 'PEPSICO', 'nombre' => 'GASEOSA PEPSI'],
            ['orden' => 129, 'clase_nombre' => 'BACKUS', 'nombre' => 'GASEOSA GUARANA'],
            ['orden' => 130, 'clase_nombre' => 'COCA-COLA', 'nombre' => 'GASEOSA SPRITE'],
            ['orden' => 131, 'clase_nombre' => 'HONG HUA', 'nombre' => 'ESPONJA ESFOLIANTE'],
            ['orden' => 132, 'clase_nombre' => 'EDGEWELL PERSONAL CARE', 'nombre' => 'AFEITADORA SCHICK'],
            ['orden' => 133, 'clase_nombre' => 'NESTLE', 'nombre' => 'LECHE CONDENSADA'],
            ['orden' => 134, 'clase_nombre' => 'MOLITALIA', 'nombre' => 'CARAMELOS AMBROSOLI'],
            ['orden' => 135, 'clase_nombre' => 'INKACROPS', 'nombre' => 'PAPAS INKACHIPS'],
            ['orden' => 136, 'clase_nombre' => 'WINTER\'S', 'nombre' => 'MARSHMALLOWS OLE OLE'],
            ['orden' => 137, 'clase_nombre' => 'SODA LIMON', 'nombre' => 'GASEOSA SODA LIMON'],
            ['orden' => 138, 'clase_nombre' => 'ALICORP', 'nombre' => 'SALSA MACBEL'],
            ['orden' => 139, 'clase_nombre' => 'ENVASADORA MAJES', 'nombre' => 'BEBIDAS KIWIFRESH'],
            ['orden' => 140, 'clase_nombre' => 'SUPERALIMENTOS', 'nombre' => 'GOMITAS TRULULU'],
            ['orden' => 141, 'clase_nombre' => 'SUPERALIMENTOS', 'nombre' => 'CARAMELOS BIG BEN'],
            ['orden' => 142, 'clase_nombre' => 'MOLITALIA', 'nombre' => 'CONSERVAS FANNY'],
            ['orden' => 143, 'clase_nombre' => 'MONDELEZ', 'nombre' => 'CHICLETS ADAMS'],
            ['orden' => 144, 'clase_nombre' => 'PROTISA', 'nombre' => 'PH NOBLE'],
            ['orden' => 145, 'clase_nombre' => 'BACKUS', 'nombre' => 'CERVEZA CUSQUEÑA'],
            ['orden' => 146, 'clase_nombre' => 'ALICORP', 'nombre' => 'LEJIA CLOROX'],
            ['orden' => 147, 'clase_nombre' => 'PAPELERA REYES', 'nombre' => 'PH PARACAS NEGRO'],
            ['orden' => 148, 'clase_nombre' => 'P.A.N.', 'nombre' => 'HARINA PAN'],
            ['orden' => 149, 'clase_nombre' => 'BACKUS', 'nombre' => 'VODKA MIKE\'S'],
            ['orden' => 150, 'clase_nombre' => 'DISTRIBUIDORA JANDY', 'nombre' => 'FOUR LOKO'],
            ['orden' => 151, 'clase_nombre' => 'COCA-COLA', 'nombre' => 'CERVEZA HEINEKEN'],
            ['orden' => 152, 'clase_nombre' => 'ISM', 'nombre' => 'AGUA CIELO'],
            ['orden' => 153, 'clase_nombre' => 'BACKUS', 'nombre' => 'CERVEZA CORONA'],
            ['orden' => 154, 'clase_nombre' => 'MOLITALIA', 'nombre' => 'TOFFE AMBROSOLI'],
            ['orden' => 155, 'clase_nombre' => 'ALICORP', 'nombre' => 'JABON DE ROPA SAN ISIDRO'],
            ['orden' => 156, 'clase_nombre' => 'ALICORP', 'nombre' => 'CONSERVAS DE PESCADO PRIMOR'],
            ['orden' => 157, 'clase_nombre' => 'ALICORP', 'nombre' => 'JABON DE ROPA POPEYE'],
            ['orden' => 158, 'clase_nombre' => 'INKACROPS', 'nombre' => 'CHIFLES INKACHIPS'],
            ['orden' => 159, 'clase_nombre' => '2 CERRITOS', 'nombre' => 'CHOCOLATE'],
            ['orden' => 160, 'clase_nombre' => 'HENKEL', 'nombre' => 'ACONDICIONADOR KONZIL'],
            ['orden' => 161, 'clase_nombre' => 'BUCKY', 'nombre' => 'SNAKS CHIFLE'],
            ['orden' => 162, 'clase_nombre' => 'LIVINI', 'nombre' => 'FLAN LIVINI'],
            ['orden' => 163, 'clase_nombre' => 'ALICORP', 'nombre' => 'HARINA BLANCA FLOR'],
            ['orden' => 164, 'clase_nombre' => 'VALLE ICA', 'nombre' => 'MENESTRAS VALLE ICA'],
            ['orden' => 165, 'clase_nombre' => 'AJE', 'nombre' => 'BIO'],
            ['orden' => 166, 'clase_nombre' => 'VALLE ICA', 'nombre' => 'FRUTOS SECOS VALLE ICA'],
            ['orden' => 167, 'clase_nombre' => 'COLGATE', 'nombre' => 'CREMA DENTAL'],
            ['orden' => 168, 'clase_nombre' => 'COLGATE', 'nombre' => 'JABON CORPORAL PROTEX'],
            ['orden' => 169, 'clase_nombre' => 'COLGATE', 'nombre' => 'CEPILLO DENTAL'],
            ['orden' => 170, 'clase_nombre' => 'AJE', 'nombre' => 'FREE TEA'],
            ['orden' => 171, 'clase_nombre' => 'COLGATE', 'nombre' => 'SUAVIZANTE'],
            ['orden' => 172, 'clase_nombre' => 'CONFITECA', 'nombre' => 'CHICLE'],
            ['orden' => 173, 'clase_nombre' => 'CONFITECA', 'nombre' => 'CHUPETIN'],
            ['orden' => 174, 'clase_nombre' => 'NESTLE', 'nombre' => 'GALLETAS NESTLE'],
            ['orden' => 175, 'clase_nombre' => 'MONDELEZ', 'nombre' => 'GALLETAS DOÑA PEPA'],
            ['orden' => 176, 'clase_nombre' => 'COCA-COLA', 'nombre' => 'FRUGOS DEL VALLE'],
            ['orden' => 177, 'clase_nombre' => 'COCA-COLA', 'nombre' => 'GASEOSA COCA COLA'],
            ['orden' => 178, 'clase_nombre' => 'PEPSICO', 'nombre' => 'SNACK PIQUEOS'],
            ['orden' => 179, 'clase_nombre' => 'PROTISA', 'nombre' => 'PAPEL TOALLA NOVA'],
            ['orden' => 180, 'clase_nombre' => 'AREQUEPAY', 'nombre' => 'TURRON AREQUEPAY'],
            ['orden' => 181, 'clase_nombre' => 'COLGATE', 'nombre' => 'JABON PALMOLIVE'],
            ['orden' => 182, 'clase_nombre' => 'CONFITECA', 'nombre' => 'CARAMELO'],
            ['orden' => 183, 'clase_nombre' => 'ISM', 'nombre' => 'GENERADE'],
            ['orden' => 184, 'clase_nombre' => 'SUPERALIMENTOS', 'nombre' => 'CHOCOLATES BIG BEN'],
            ['orden' => 185, 'clase_nombre' => 'SUPERALIMENTOS', 'nombre' => 'CARAMELO OKA LOKA'],
            ['orden' => 186, 'clase_nombre' => 'ALICORP', 'nombre' => 'ESCENCIA VAINILLA UMSHA'],
            ['orden' => 187, 'clase_nombre' => 'CLASICO', 'nombre' => 'GANCHOS DE ROPA'],
            ['orden' => 188, 'clase_nombre' => 'SOFTYS', 'nombre' => 'TOALLA HIGIENICA'],
            ['orden' => 189, 'clase_nombre' => 'PROTISA', 'nombre' => 'PH HIGIENOL'],
            ['orden' => 190, 'clase_nombre' => 'UNILEVER', 'nombre' => 'CREMAS PONDS'],
            ['orden' => 191, 'clase_nombre' => 'ALICORP', 'nombre' => 'ROMEX'],
            ['orden' => 192, 'clase_nombre' => 'NESTLE', 'nombre' => 'MAGGI'],
            ['orden' => 193, 'clase_nombre' => 'ALICORP', 'nombre' => 'LAVAGGI'],
            ['orden' => 194, 'clase_nombre' => 'ARCOR', 'nombre' => 'CHICLE ARCOR'],
            ['orden' => 195, 'clase_nombre' => 'ARCOR', 'nombre' => 'CARAMELO ARCOR'],
            ['orden' => 196, 'clase_nombre' => 'ARCOR', 'nombre' => 'GOMITAS ARCOR'],
            ['orden' => 197, 'clase_nombre' => 'ARCOR', 'nombre' => 'CHOCOLATE ARCOR'],
            ['orden' => 198, 'clase_nombre' => 'GLORIA', 'nombre' => 'MERMELADA GLORIA'],
            ['orden' => 199, 'clase_nombre' => 'BACKUS', 'nombre' => 'AGUA MINERAL'],
            ['orden' => 200, 'clase_nombre' => 'PEPSICO', 'nombre' => 'SNACK TOR-TEES'],
            ['orden' => 201, 'clase_nombre' => 'CONFITECA', 'nombre' => 'MUSS'],
            ['orden' => 202, 'clase_nombre' => 'PROCTER & GAMBLE (P&G)', 'nombre' => 'SUAVIZANTE DOWNY'],
            ['orden' => 203, 'clase_nombre' => 'PROCTER & GAMBLE (P&G)', 'nombre' => 'SHAMPOO PANTENE'],
            ['orden' => 204, 'clase_nombre' => 'PROCTER & GAMBLE (P&G)', 'nombre' => 'SHAMPOO H&S'],
            ['orden' => 205, 'clase_nombre' => 'PROCTER & GAMBLE (P&G)', 'nombre' => 'GILLETE'],
            ['orden' => 206, 'clase_nombre' => 'EL ROJITO', 'nombre' => 'DESCARTABLES'],
            ['orden' => 207, 'clase_nombre' => 'MI FARMA', 'nombre' => 'HENO DE PRAVIA'],
            ['orden' => 208, 'clase_nombre' => 'QUIMPAC', 'nombre' => 'SAL MARINA'],
            ['orden' => 209, 'clase_nombre' => 'BACKUS', 'nombre' => 'CERVEZA PILSEN'],
            ['orden' => 210, 'clase_nombre' => 'ISM', 'nombre' => 'GASEOSA KR'],
            ['orden' => 211, 'clase_nombre' => 'NESTLE', 'nombre' => 'ECCO NESTLE'],
            ['orden' => 212, 'clase_nombre' => 'NESTLE', 'nombre' => 'MILO NESTLE'],
            ['orden' => 213, 'clase_nombre' => 'NESTLE', 'nombre' => 'NESQUIK NESTLE'],
            ['orden' => 214, 'clase_nombre' => 'NESTLE', 'nombre' => 'KIRMA NESTLE'],
            ['orden' => 215, 'clase_nombre' => 'ISM', 'nombre' => 'AGUA LOA'],
            ['orden' => 216, 'clase_nombre' => 'ALICORP', 'nombre' => 'JABON DE ROPA BOLIVAR'],
            ['orden' => 217, 'clase_nombre' => 'ALICORP', 'nombre' => 'ACEITE PRIMOR'],
            ['orden' => 218, 'clase_nombre' => 'MEGAPLAST', 'nombre' => 'BOLSA BASURA'],
            ['orden' => 219, 'clase_nombre' => 'ALICORP', 'nombre' => 'PANETON SAYON'],
            ['orden' => 220, 'clase_nombre' => 'INCASUR', 'nombre' => 'CHOCOLATE P/ TAZA'],
            ['orden' => 221, 'clase_nombre' => 'ALICORP', 'nombre' => 'FIDEOS NICOLINI'],
            ['orden' => 222, 'clase_nombre' => 'AJE', 'nombre' => 'GASEOSA LATA'],
            ['orden' => 223, 'clase_nombre' => 'AJE', 'nombre' => 'ENERGIZANTE'],
            ['orden' => 224, 'clase_nombre' => 'SOMELE', 'nombre' => 'ARROZ EN SACO'],
            ['orden' => 225, 'clase_nombre' => 'POMALCA', 'nombre' => 'AZUCAR EN SACO'],
            ['orden' => 226, 'clase_nombre' => 'KIMBERLY-CLARK', 'nombre' => 'TOALLAS HIGIENICAS'],
            ['orden' => 227, 'clase_nombre' => 'NESTLE', 'nombre' => 'WAFER'],
            ['orden' => 228, 'clase_nombre' => 'BORANI', 'nombre' => 'PINZAS'],
        ];
    }
}
